### ISSUE TITLE
Code jammed sideways???

### ISSUE THREAD

**Issue by Racer1Tn** [jgoergen/CamBot#1]
I'm not a developer, but I do have a programming degree. Just what does the comment "You will have to be able to run .net 4 code, and you will also have to install the EMGU libs ( linked above ) **or even better, use Nuget to pull down the latest EMGU.CV libs. Warning. This is hacked together code at the moment, jammed sideways into an example from EMGU." mean?**
Do you have any instructions or details on the steps you actually used to make this work?

**Comment by jgoergen** [comment]
Sorry, really what I mean by "jammed in sideways" is that I took their example for motion detection and added what I needed to communicate with the bot ( serial communication ) and asses the motion detection feedback to come up with the commands to send. Also I'm insinuating that I didn't spend alot of time trying to craft up some beautiful, well thought out code. I plan on taking this working prototype and doing a second pass on the code to make it cleaner and more my own thing, and less just a modified example from someone else.

Just incase the rest of it is confusing I'll elaborate on that as well:
"You will need to be able to run .net 4 code" as in, you will need Visual Studio ( and the ability to build .Net 4 code. ) 

"and you will also have to install the EMGU libs ( linked above ) or even better, use Nuget to pull down the latest EMGU.CV libs" meaning; Once you have the project cloned and opened in visual studio you will most likely have reference errors because you do not have EMGU setup and the dll's that are needed. This can be resolved by installing EMGU and finding the dll's you need / adding references to them manually. Or you can lookup EMGU on Nuget ( or just restore the package via Nuget. ) 

Please give this a try and let me know if you have issues ( also if you get past any issues, what you did ) so I can update the description to better describe what is necessary for getting it running. 

It's hard for me to know exactly what your experience will be with it as I went the long way getting this all running, and I'm hoping you won't have to now that I have arrived at the solutions that I have provided here.
